### PR TITLE
Set finalizer for Scratch

### PR DESCRIPTION
**Pull request by jmdacruz**
I'm currently doing this myself so that I can ensure C memory is released: Would it make sense to set the finalizer for the Scratch space in `NewScratch`, so that if the Scratch object context is no longer valid then the scratch space memory is reclaimed?

### CODE REVIEW

**Comment by jmdacruz** [comment]
A similar approach could be to do this on the `hsAllocScratch` method instead (with a finalizer calling `hsFreeScratch`)

**Comment by flier** [comment]
I agree that this is another way to use it, but it would be a break change of the existing API, so maybe we can add a `NewManagedScratch` function to avoid?

**Comment by jmdacruz** [comment]
Sounds good @flier, I'll make that change. Do you think we could do something similar for `NewBlockDatabase` and `NewStreamDatabase`?  The `Close()` method for both seems to use `hsFreeDatabase`, which will free memory. Should I also add a `NewManagedBlockDatabase` and `NewManagedStreamDatabase`?

**Comment by jmdacruz** [comment]
@flier I changed my commit with your suggestion, plus I added the `NewManagedBlockDatabase` and `NewManagedStreamDatabase` helper methods too. I also modified the tests in hyperscan/runtime_test.go so that we can test both style of constructors with the same test cases.

**Comment by flier** [comment]
Looks good, seems like there are some conflicts in the test cases?

Thanks :)

**Pull request merged**
